language: elixir
elixir:
  - 1.5

dist: trusty

sudo: true

cache: cargo

otp_release:
  - 20.0

services:
  - postgresql

addons:
  postgresql: 9.5
  apt:
    packages:
     - gdb
     - apport
     - libc6-dev
     - libc-dbg
     - gdb-doc
     - gdbserver

env:
  - POSTGRES_PASSWORD="" MIX_ENV=test

before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup update
  - rustc -Vv
  - cargo -V
  - rustup component add rust-src
  - export RUST_SRC_PATH=`rustc --print sysroot`/lib/rustlib/src/rust/src
  - export RUST_BACKTRACE=1
  - mix deps.get --only test

script:
  - mix ecto.create
  - mix ecto.create
  - mix ecto.migrate
  - mix test
